// import 'package:travelerdubai/model/tours.dart';

// List<TourModel> demoTours = [
//   TourModel(
//     tourId: 1,
//     countryId: 1,
//     countryName: 'Country 1',
//     cityId: 101,
//     cityName: 'City 1',
//     tourName: 'Tour 1',
//     reviewCount: 25,
//     rating: 4.5,
//     duration: '2 hours',
//     departurePoint: 'Main Square',
//     reportingTime: '10:00 AM',
//     tourLanguage: 'English',
//     imagePath: 'tour1_image_path',
//     imageCaptionName: 'Image 1',
//     cityTourTypeId: "1",
//     cityTourType: 'City Tour',
//     tourDescription: 'Explore the city...',
//     tourInclusion: 'Transportation, guide...',
//     tourShortDescription: 'City tour with guide',
//     raynaToursAdvantage: 'Skip the lines...',
//     whatsInThisTour: 'Sightseeing, history...',
//     importantInformation: 'Bring water...',
//     itenararyDescription: 'Visit landmarks...',
//     usefulInformation: 'Wear comfortable shoes...',
//     faqDetails: 'Questions and answers...',
//     termsAndConditions: 'Cancellation policy...',
//     cancellationPolicyName: 'Flexible',
//     cancellationPolicyDescription: 'Cancel up to 24 hours...',
//     childCancellationPolicyName: 'Same as adult',
//     childCancellationPolicyDescription: 'Child cancellation policy...',
//     childAge: '3 - 12 years',
//     infantAge: 'Under 3 years',
//     infantCount: '1 infant per adult',
//     isSlot: 'false',
//     onlyChild: 'false',
//     contractId: 1001,
//     tourImages: [
//       TourImage(
//         tourId: 1,
//         imagePath: 'tour1_image1_path',
//         imageCaptionName: 'Image 1',
//         isFrontImage: 'true',
//         isBannerImage: 'false',
//         isBannerRotateImage: 'false',
//       ),
//       TourImage(
//         tourId: 1,
//         imagePath: 'tour1_image2_path',
//         imageCaptionName: 'Image 2',
//         isFrontImage: 'false',
//         isBannerImage: 'true',
//         isBannerRotateImage: 'false',
//       ),
//     ],
//     tourReview: [
//       TourReview(
//         id: 1,
//         tourId: 1,
//         reviewId: 101,
//         reviewTitle: 'Excellent Experience',
//         reviewContent: 'Had a great time...',
//         visitMonth: 'July 2023',
//         rating: 5.0,
//         imagePath: 'review_image1_path',
//         guestName: 'John Doe',
//       ),
//       TourReview(
//         id: 2,
//         tourId: 1,
//         reviewId: 102,
//         reviewTitle: 'Informative Tour',
//         reviewContent: 'Learned a lot about...',
//         visitMonth: 'August 2023',
//         rating: 4.0,
//         imagePath: 'review_image2_path',
//         guestName: 'Jane Smith',
//       ),
//     ],
//   ),
//   TourModel(
//     tourId: 2,
//     countryId: 2,
//     countryName: 'Country 2',
//     cityId: 201,
//     cityName: 'City 2',
//     tourName: 'Historical Tour',
//     reviewCount: 18,
//     rating: 4.2,
//     duration: '3 hours',
//     departurePoint: 'Historical Center',
//     reportingTime: '9:30 AM',
//     tourLanguage: 'Local Language',
//     imagePath: 'tour2_image_path',
//     imageCaptionName: 'Historical Landmark',
//     cityTourTypeId: "2",
//     cityTourType: 'Historical Tour',
//     tourDescription: 'Explore the rich history...',
//     tourInclusion: 'Guided tour, entrance fees...',
//     tourShortDescription: 'Learn about local history',
//     raynaToursAdvantage: 'Expert guides...',
//     whatsInThisTour: 'Historical sites, artifacts...',
//     importantInformation: 'Wear comfortable clothes...',
//     itenararyDescription: 'Visit historical landmarks...',
//     usefulInformation: 'Bring a camera...',
//     faqDetails: 'Common questions about the tour...',
//     termsAndConditions: 'Refund policy and terms...',
//     cancellationPolicyName: 'Moderate',
//     cancellationPolicyDescription: 'Cancel up to 48 hours...',
//     childCancellationPolicyName: '50% refund',
//     childCancellationPolicyDescription: 'Child cancellation policy...',
//     childAge: '6 - 14 years',
//     infantAge: 'Under 6 years',
//     infantCount: 'Infants not recommended',
//     isSlot: 'false',
//     onlyChild: 'false',
//     contractId: 2001,
//     tourImages: [
//       TourImage(
//         tourId: 2,
//         imagePath: 'tour2_image1_path',
//         imageCaptionName: 'Historical Site 1',
//         isFrontImage: 'true',
//         isBannerImage: 'false',
//         isBannerRotateImage: 'false',
//       ),
//       TourImage(
//         tourId: 2,
//         imagePath: 'tour2_image2_path',
//         imageCaptionName: 'Historical Site 2',
//         isFrontImage: 'false',
//         isBannerImage: 'true',
//         isBannerRotateImage: 'false',
//       ),
//     ],
//     tourReview: [
//       TourReview(
//         id: 3,
//         tourId: 2,
//         reviewId: 201,
//         reviewTitle: 'Fascinating Tour',
//         reviewContent: 'A must-do for history enthusiasts...',
//         visitMonth: 'June 2023',
//         rating: 4.7,
//         imagePath: 'review_image3_path',
//         guestName: 'Michael Brown',
//       ),
//       TourReview(
//         id: 4,
//         tourId: 2,
//         reviewId: 202,
//         reviewTitle: 'Informative and Enjoyable',
//         reviewContent: 'Learned so much about the city\'s history...',
//         visitMonth: 'September 2023',
//         rating: 4.5,
//         imagePath: 'review_image4_path',
//         guestName: 'Emily Johnson',
//       ),
//     ],
//   ),
//   TourModel(
//     tourId: 6,
//     countryId: 3,
//     countryName: 'Country 3',
//     cityId: 301,
//     cityName: 'City 3',
//     tourName: 'Adventure Expedition',
//     reviewCount: 10,
//     rating: 4.8,
//     duration: 'Full Day',
//     departurePoint: 'Adventure Center',
//     reportingTime: '8:00 AM',
//     tourLanguage: 'English',
//     imagePath: 'tour6_image_path',
//     imageCaptionName: 'Adventure Scene',
//     cityTourTypeId: "3",
//     cityTourType: 'Adventure Tour',
//     tourDescription: 'Embark on an exciting adventure...',
//     tourInclusion: 'Equipment rental, guides...',
//     tourShortDescription: 'Thrilling outdoor activities',
//     raynaToursAdvantage: 'Safety measures in place...',
//     whatsInThisTour: 'Ziplining, rock climbing...',
//     importantInformation: 'Wear appropriate attire...',
//     itenararyDescription: 'Explore natural landscapes...',
//     usefulInformation: 'Bring sunscreen and water...',
//     faqDetails: 'Frequently asked questions...',
//     termsAndConditions: 'Cancellation policy details...',
//     cancellationPolicyName: 'Strict',
//     cancellationPolicyDescription: 'No refund after booking...',
//     childCancellationPolicyName: 'Not recommended for children',
//     childCancellationPolicyDescription: 'Child age policy...',
//     childAge: 'Not suitable for children',
//     infantAge: 'Not suitable for infants',
//     infantCount: 'Infants not allowed',
//     isSlot: 'false',
//     onlyChild: 'false',
//     contractId: 3001,
//     tourImages: [
//       TourImage(
//         tourId: 6,
//         imagePath: 'tour6_image1_path',
//         imageCaptionName: 'Adventure Activity 1',
//         isFrontImage: 'true',
//         isBannerImage: 'false',
//         isBannerRotateImage: 'false',
//       ),
//       TourImage(
//         tourId: 6,
//         imagePath: 'tour6_image2_path',
//         imageCaptionName: 'Adventure Activity 2',
//         isFrontImage: 'false',
//         isBannerImage: 'true',
//         isBannerRotateImage: 'false',
//       ),
//     ],
//     tourReview: [
//       TourReview(
//         id: 11,
//         tourId: 6,
//         reviewId: 601,
//         reviewTitle: 'Thrilling Experience',
//         reviewContent: 'Adrenaline rush throughout...',
//         visitMonth: 'October 2023',
//         rating: 5.0,
//         imagePath: 'review_image11_path',
//         guestName: 'Sarah Davis',
//       ),
//       TourReview(
//         id: 12,
//         tourId: 6,
//         reviewId: 602,
//         reviewTitle: 'Unforgettable Adventure',
//         reviewContent: 'Had a blast on every activity...',
//         visitMonth: 'August 2023',
//         rating: 4.9,
//         imagePath: 'review_image12_path',
//         guestName: 'Robert Wilson',
//       ),
//     ],
//   ),
//   TourModel(
//     tourId: 7,
//     countryId: 4,
//     countryName: 'Country 4',
//     cityId: 401,
//     cityName: 'City 4',
//     tourName: 'Culinary Walking Tour',
//     reviewCount: 14,
//     rating: 4.9,
//     duration: '3 hours',
//     departurePoint: 'Downtown Square',
//     reportingTime: '11:30 AM',
//     tourLanguage: 'English, Local Language',
//     imagePath: 'tour7_image_path',
//     imageCaptionName: 'Food Tasting Experience',
//     cityTourTypeId: "4",
//     cityTourType: 'Food Tour',
//     tourDescription: 'Embark on a gastronomic adventure...',
//     tourInclusion: 'Food tastings, local guide...',
//     tourShortDescription: 'Savor the city\'s flavors',
//     raynaToursAdvantage: 'Handpicked eateries and dishes...',
//     whatsInThisTour: 'Culinary journey, cultural insights...',
//     importantInformation: 'Inform of dietary restrictions...',
//     itenararyDescription: 'Visit renowned restaurants...',
//     usefulInformation: 'Wear comfortable shoes...',
//     faqDetails: 'Answers to common questions...',
//     termsAndConditions: 'Booking terms and policies...',
//     cancellationPolicyName: 'Moderate',
//     cancellationPolicyDescription: 'Cancel up to 48 hours...',
//     childCancellationPolicyName: 'Children allowed',
//     childCancellationPolicyDescription: 'Child age and policy...',
//     childAge: '5 - 12 years',
//     infantAge: 'Not suitable for infants',
//     infantCount: 'Infants not recommended',
//     isSlot: 'false',
//     onlyChild: 'false',
//     contractId: 3004,
//     tourImages: [
//       TourImage(
//         tourId: 7,
//         imagePath: 'tour7_image1_path',
//         imageCaptionName: 'Food Tasting 1',
//         isFrontImage: 'true',
//         isBannerImage: 'false',
//         isBannerRotateImage: 'false',
//       ),
//       TourImage(
//         tourId: 7,
//         imagePath: 'tour7_image2_path',
//         imageCaptionName: 'Food Tasting 2',
//         isFrontImage: 'false',
//         isBannerImage: 'true',
//         isBannerRotateImage: 'false',
//       ),
//     ],
//     tourReview: [
//       TourReview(
//         id: 17,
//         tourId: 7,
//         reviewId: 607,
//         reviewTitle: 'Delicious Journey',
//         reviewContent: 'A feast for the taste buds...',
//         visitMonth: 'June 2023',
//         rating: 5.0,
//         imagePath: 'review_image17_path',
//         guestName: 'Jessica Martinez',
//       ),
//       TourReview(
//         id: 18,
//         tourId: 7,
//         reviewId: 608,
//         reviewTitle: 'Food Lover\'s Dream',
//         reviewContent: 'Exquisite food and memorable stories...',
//         visitMonth: 'March 2023',
//         rating: 4.8,
//         imagePath: 'review_image18_path',
//         guestName: 'Daniel Lee',
//       ),
//     ],
//   ),
//   TourModel(
//     tourId: 11,
//     countryId: 2,
//     countryName: 'Country 2',
//     cityId: 201,
//     cityName: 'City 2',
//     tourName: 'Mountain Hiking Adventure',
//     reviewCount: 12,
//     rating: 4.8,
//     duration: 'Full Day',
//     departurePoint: 'Trailhead Parking',
//     reportingTime: '7:00 AM',
//     tourLanguage: 'English',
//     imagePath: 'tour11_image_path',
//     imageCaptionName: 'Hiking Along the Summit',
//     cityTourTypeId: "2",
//     cityTourType: 'Outdoor Activity',
//     tourDescription: 'Embark on a thrilling hike...',
//     tourInclusion: 'Guided hike, safety gear...',
//     tourShortDescription: 'Conquer the mountain peaks',
//     raynaToursAdvantage: 'Experienced guides, stunning views...',
//     whatsInThisTour: 'Scenic trails, nature exploration...',
//     importantInformation: 'Wear appropriate footwear...',
//     itenararyDescription: 'Ascend the summit, enjoy a picnic...',
//     usefulInformation: 'Carry water and snacks...',
//     faqDetails: 'Answers to common questions...',
//     termsAndConditions: 'Booking terms and policies...',
//     cancellationPolicyName: 'Flexible',
//     cancellationPolicyDescription: 'Cancel up to 24 hours...',
//     childCancellationPolicyName: 'Children allowed',
//     childCancellationPolicyDescription: 'Child age and policy...',
//     childAge: '8 - 16 years',
//     infantAge: 'Not suitable for infants',
//     infantCount: 'Infants not recommended',
//     isSlot: 'false',
//     onlyChild: 'false',
//     contractId: 3011,
//     tourImages: [
//       TourImage(
//         tourId: 11,
//         imagePath: 'https://source.unsplash.com/random/bali,night',
//         imageCaptionName: 'Hiking Trail 1',
//         isFrontImage: 'true',
//         isBannerImage: 'false',
//         isBannerRotateImage: 'false',
//       ),
//       TourImage(
//         tourId: 11,
//         imagePath: 'https://source.unsplash.com/random/?newyork,night',
//         imageCaptionName: 'Hiking Trail 2',
//         isFrontImage: 'false',
//         isBannerImage: 'true',
//         isBannerRotateImage: 'false',
//       ),
//       TourImage(
//         tourId: 11,
//         imagePath: 'https://source.unsplash.com/random/australia,night',
//         imageCaptionName: 'Hiking Trail 1',
//         isFrontImage: 'true',
//         isBannerImage: 'false',
//         isBannerRotateImage: 'false',
//       ),
//       TourImage(
//         tourId: 11,
//         imagePath: 'https://source.unsplash.com/random/?maldives,night',
//         imageCaptionName: 'Hiking Trail 2',
//         isFrontImage: 'false',
//         isBannerImage: 'true',
//         isBannerRotateImage: 'false',
//       ),
//     ],
//     tourReview: [
//       TourReview(
//         id: 21,
//         tourId: 11,
//         reviewId: 611,
//         reviewTitle: 'Unforgettable Hike',
//         reviewContent: 'Breathtaking views and great guides...',
//         visitMonth: 'August 2023',
//         rating: 4.9,
//         imagePath: 'https://source.unsplash.com/random/dubai,night',
//         guestName: 'Alex Turner',
//       ),
//       TourReview(
//         id: 22,
//         tourId: 11,
//         reviewId: 612,
//         reviewTitle: 'Nature Lover\'s Paradise',
//         reviewContent: 'Loved being immersed in nature...',
//         visitMonth: 'July 2023',
//         rating: 5.0,
//         imagePath: 'https://source.unsplash.com/random/bali,night',
//         guestName: 'Sophia Rodriguez',
//       ),
//       TourReview(
//         id: 22,
//         tourId: 11,
//         reviewId: 612,
//         reviewTitle: 'Nature Lover\'s Paradise',
//         reviewContent: 'Loved being immersed in nature...',
//         visitMonth: 'July 2023',
//         rating: 5.0,
//         imagePath: 'https://source.unsplash.com/random/australia,night',
//         guestName: 'Sophia Rodriguez',
//       ),
//       TourReview(
//         id: 22,
//         tourId: 11,
//         reviewId: 612,
//         reviewTitle: 'anime Lover\'s Paradise',
//         reviewContent: 'Loved being immersed in nature...',
//         visitMonth: 'July 2023',
//         rating: 5.0,
//         imagePath: 'https://source.unsplash.com/random/maldives,night',
//         guestName: 'Sophia Rodriguez',
//       ),
//     ],
//   ),
//   // Tour 12
//   TourModel(
//     tourId: 12,
//     countryId: 1,
//     countryName: 'Country 1',
//     cityId: 101,
//     cityName: 'City 1',
//     tourName: 'Cultural Heritage Tour',
//     reviewCount: 10,
//     rating: 4.7,
//     duration: 'Half Day',
//     departurePoint: 'City Center',
//     reportingTime: '10:00 AM',
//     tourLanguage: 'English, Local Language',
//     imagePath: 'tour12_image_path',
//     imageCaptionName: 'Historic Landmarks',
//     cityTourTypeId: "1",
//     cityTourType: 'Cultural Tour',
//     tourDescription: 'Explore the city\'s rich history...',
//     tourInclusion: 'Knowledgeable guide, entry fees...',
//     tourShortDescription: 'Discover the city\'s heritage',
//     raynaToursAdvantage: 'Insightful commentary, iconic sites...',
//     whatsInThisTour: 'Museums, monuments, local stories...',
//     importantInformation: 'Respect dress codes for sites...',
//     itenararyDescription: 'Visit landmarks, learn about history...',
//     usefulInformation: 'Wear comfortable clothing...',
//     faqDetails: 'Answers to common questions...',
//     termsAndConditions: 'Booking terms and policies...',
//     cancellationPolicyName: 'Moderate',
//     cancellationPolicyDescription: 'Cancel up to 48 hours...',
//     childCancellationPolicyName: 'Children allowed',
//     childCancellationPolicyDescription: 'Child age and policy...',
//     childAge: '6 - 14 years',
//     infantAge: 'Infants allowed under 5',
//     infantCount: 'Limited spots for infants',
//     isSlot: 'false',
//     onlyChild: 'false',
//     contractId: 3012,
//     tourImages: [
//       TourImage(
//         tourId: 12,
//         imagePath: 'tour12_image1_path',
//         imageCaptionName: 'Historic Site 1',
//         isFrontImage: 'true',
//         isBannerImage: 'false',
//         isBannerRotateImage: 'false',
//       ),
//       TourImage(
//         tourId: 12,
//         imagePath: 'tour12_image2_path',
//         imageCaptionName: 'Historic Site 2',
//         isFrontImage: 'false',
//         isBannerImage: 'true',
//         isBannerRotateImage: 'false',
//       ),
//     ],
//     tourReview: [
//       TourReview(
//         id: 23,
//         tourId: 12,
//         reviewId: 613,
//         reviewTitle: 'Educational and Enjoyable',
//         reviewContent: 'Learned a lot about the city\'s history...',
//         visitMonth: 'September 2023',
//         rating: 4.7,
//         imagePath: 'review_image23_path',
//         guestName: 'Oliver Williams',
//       ),
//       TourReview(
//         id: 24,
//         tourId: 12,
//         reviewId: 614,
//         reviewTitle: 'Insightful Tour',
//         reviewContent: 'Impressed by the depth of information...',
//         visitMonth: 'October 2023',
//         rating: 4.8,
//         imagePath: 'review_image24_path',
//         guestName: 'Emma Brown',
//       ),
//     ],
//   ),
//   // Tour 13
//   TourModel(
//     tourId: 13,
//     countryId: 5,
//     countryName: 'Country 5',
//     cityId: 501,
//     cityName: 'City 5',
//     tourName: 'Sunset Cruise Experience',
//     reviewCount: 9,
//     rating: 4.5,
//     duration: '2 hours',
//     departurePoint: 'Harbor Dock',
//     reportingTime: '5:30 PM',
//     tourLanguage: 'English',
//     imagePath: 'tour13_image_path',
//     imageCaptionName: 'Sunset Over the Horizon',
//     cityTourTypeId: "5",
//     cityTourType: 'Cruise Tour',
//     tourDescription: 'Sail along the coast and watch...',
//     tourInclusion: 'Guided cruise, refreshments...',
//     tourShortDescription: 'Witness a mesmerizing sunset',
//     raynaToursAdvantage: 'Luxury yacht, onboard entertainment...',
//     whatsInThisTour: 'Relaxation, sunset views, photo ops...',
//     importantInformation: 'Arrive 30 minutes before...',
//     itenararyDescription: 'Cruise along the coastline...',
//     usefulInformation: 'Carry a light jacket...',
//     faqDetails: 'Answers to common questions...',
//     termsAndConditions: 'Booking terms and policies...',
//     cancellationPolicyName: 'Flexible',
//     cancellationPolicyDescription: 'Cancel up to 24 hours...',
//     childCancellationPolicyName: 'Children allowed',
//     childCancellationPolicyDescription: 'Child age and policy...',
//     childAge: '5 - 12 years',
//     infantAge: 'Infants allowed under 5',
//     infantCount: 'Limited spots for infants',
//     isSlot: 'false',
//     onlyChild: 'false',
//     contractId: 3013,
//     tourImages: [
//       TourImage(
//         tourId: 13,
//         imagePath: 'tour13_image1_path',
//         imageCaptionName: 'Sunset Cruise 1',
//         isFrontImage: 'true',
//         isBannerImage: 'false',
//         isBannerRotateImage: 'false',
//       ),
//       TourImage(
//         tourId: 13,
//         imagePath: 'tour13_image2_path',
//         imageCaptionName: 'Sunset Cruise 2',
//         isFrontImage: 'false',
//         isBannerImage: 'true',
//         isBannerRotateImage: 'false',
//       ),
//     ],
//     tourReview: [
//       TourReview(
//         id: 25,
//         tourId: 13,
//         reviewId: 615,
//         reviewTitle: 'Breathtaking Sunset',
//         reviewContent: 'Perfect evening with stunning views...',
//         visitMonth: 'November 2023',
//         rating: 4.6,
//         imagePath: 'review_image25_path',
//         guestName: 'Liam Taylor',
//       ),
//       TourReview(
//         id: 26,
//         tourId: 13,
//         reviewId: 616,
//         reviewTitle: 'Magical Cruise',
//         reviewContent: 'Unforgettable sunset experience...',
//         visitMonth: 'December 2023',
//         rating: 4.4,
//         imagePath: 'review_image26_path',
//         guestName: 'Ava Martinez',
//       ),
//     ],
//   ),
//   // ... add more tours here
// ];
